import type { Metadata } from "next";
import NavLinkList from "./_/components/nav-link/nav-link-list";
import { ModalProvider } from "./_/providers/modal-provider";

export const metadata: Metadata = {
  title: "Core",
  description: "Generated by core app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ModalProvider>
      <div className="flex gap-x-3 p-3 md:gap-x-5 md:p-5">
        <NavLinkList />
        <div className="grid flex-1 grid-cols-1 gap-3">{children}</div>
      </div>
    </ModalProvider>
  );
}
