import { ThemeProvider } from "@/context/theme-context";
import { SupabaseProvider } from "@/providers/supabase-provider";
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import Header from "./_components/header/header";
import "./globals.css";

const vazir = Vazirmatn({
  variable: "--font-vazir",
});

export const metadata: Metadata = {
  title: "Car Rent",
  description: "Generated by car rent app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className={`${vazir.variable} antialiased`}>
        <SupabaseProvider>
          <ThemeProvider>
            <Header />
            {children}
          </ThemeProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
